CREATE DATABASE IF NOT EXISTS MONTE_SEU_PC;

CREATE TABLE IF NOT EXISTS USUARIO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha BINARY(32) NOT NULL,
    ruido CHAR(20) NOT NULL UNIQUE,
    ehAdmin BOOL DEFAULT 0,
    token BINARY(8) UNIQUE,
    sessao TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COMPUTADORES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    dono INT FOREIGN KEY REFERENCES USUARIO(id)
);

CREATE TABLE IF NOT EXISTS PECAS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    marca VARCHAR(255) NOT NULL,
    tipo ENUM('Placa-mãe', 'Processador', 'Memória', 'Fonte') NOT NULL,
    CONSTRAINT nomeComp UNIQUE(nome,marca)
);

CREATE TABLE IF NOT EXISTS PROPRIEDADE (
    nome VARCHAR(255) PRIMARY KEY,
    descricao TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS INCOMPAT_PROP (
    prop1 VARCHAR(255) FOREIGN KEY REFERENCES PROPRIEDADE(nome),
    prop2 VARCHAR(255) FOREIGN KEY REFERENCES PROPRIEDADE(nome),
    PRIMARY KEY (prop1, prop2),
    CHECK(prop1<>prop2)
);

CREATE TABLE IF NOT EXISTS COMP_PECAS (
    comp INT FOREIGN KEY REFERENCES COMPUTADORES(id),
    peca INT FOREIGN KEY REFERENCES PECAS(id),
    PRIMARY KEY (comp, peca)
);

